export const UPDATE_PHASE = "UPDATE_PHASE";
export const UPDATE_EDIT_GRAPH = "UPDATE_EDIT_GRAPH";
export const UPDATE_INPUT = "UPDATE_INPUT";
export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_ALGORITHM_PROGRESS = "UPDATE_ALGORITHM_PROGRESS";
export const UPDATE_FORM_INPUT = "UPDATE_FORM_INPUT";
export const UPDATE_SELECTED_ALGORITHM = "UPDATE_SELECTED_ALGORITHM";
export const RESET = "RESET";